# Generated by Django 5.1 on 2024-10-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.TextField()),
                ("about_you", models.TextField(blank=True, null=True)),
                (
                    "home_type",
                    models.CharField(
                        choices=[("rent", "Rent"), ("own", "Own")], max_length=4
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("two_wheeler", "2 Wheeler"),
                            ("four_wheeler", "4 Wheeler"),
                            ("other", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "health_details",
                    models.CharField(
                        choices=[
                            ("prolonged_health_issues", "Prolonged health issues"),
                            ("seasonal_flu", "Prone to seasonal flu"),
                            ("general_health_issues", "General health issues"),
                        ],
                        max_length=25,
                    ),
                ),
            ],
        ),
    ]
