# Generated by Django 5.1 on 2024-10-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_userdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="about_you",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="gender",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="health_details",
            field=models.CharField(
                choices=[
                    ("prolonged_health_issues", "Prolonged health issues"),
                    ("seasonal_flu", "Prone to seasonal flu"),
                    ("general_health_issues", "General health issues"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="home_type",
            field=models.CharField(
                choices=[("rent", "Rent"), ("own", "Own")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="userdetails",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("two_wheeler", "2 Wheeler"),
                    ("four_wheeler", "4 Wheeler"),
                    ("other", "Other"),
                ],
                max_length=15,
            ),
        ),
    ]
